CFLAGS:=-Os -I../
LDFLAGS:= -lgcov --coverage

$(PROGRAM): $(SRC)
	$(CC) $(SRC) $(CFLAGS) $(LDFLAGS) -o $@

clean:
	rm -f $(PROGRAM)

.PHONY: coverage
coverage: $(TEST)
	lcov --zerocounters -d .
	lcov --capture --initial -d . --output-file coverage.info
	./$(TEST)
	lcov --capture -d . --output-file coverage.info
	mkdir -p coverage
	cd coverage && genhtml ../coverage.info
	sensible-browser coverage/index.html
