"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# MacOS dependances for non-bundled package:
# pip3 install pyserial pyyaml idle Pillow
# brew install python-tk

# To create a MacOS OSM GUI App, run:
# python3 macos_setup.py py2app
# The app will be in dist/config_gui.app

# Once bundled the .app has no dependances

# To distribute, I suggest tarballing it up:
# tar -C dist -cvjf config_gui.app.tar.bz2 config_gui.app
# MacOS GUI extracts tarballs automatically when you open it.
# Then tell the customer to drag the resulting .app into their Applications folder.
# We should work on a .dmg or .pkg, though.

# If you have issues with tcl/tk, make sure your
# build macOS instance has the latest Python from python.org.

from setuptools import setup

APP = ['config_gui.py']
DATA_FILES = [
 'osm_pictures',
 'yaml_files',
 'config_database'
]
OPTIONS = {
    'iconfile': 'osm_pictures/macos-osm.icns',
    'plist':    {'NSRequiresAquaSystemAppearance': False}, # Dark mode support
    'includes': ['PIL','binding','crccheck.crc','csv','datetime','idlelib.tooltip','imp','io','json','logging','modbus_db','modbus_funcs','os','platform','random','re','serial','serial.tools.list_ports','setuptools','signal','sqlite3','stat','string','subprocess','sys','threading','time','tkinter','tkinter.filedialog','tkinter.messagebox','tkinter.ttk','traceback','webbrowser','yaml', 'multiprocessing'],
    'packages': ['tkinter'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

