"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# MacOS dependances:
# pip3 install pyserial pyyaml idle Pillow
# brew install python-tk

# To create a MacOS OSM GUI App, run:
# python3 macos_setup.py py2app
# The app will be in dist/config_gui.app

from setuptools import setup

APP = ['config_gui.py']
DATA_FILES = ['osm_pictures',
 'yaml_files',
 'config_database',
 'binding.py',
 'complete.bin',
 'modbus_db.py',
 'modbus_funcs.py',
 'static_program.sh',
 'create_gui_exe.sh',
 'create_static_stm.sh',
 'static_program.sh']
OPTIONS = {'iconfile': 'osm_pictures/logos/macos-osm.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
